<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(Disabled - please add content in default language!)' => '',
    '<strong>Legal</strong> module - administration' => '',
    'Accept' => '',
    'Accept button label' => '',
    'Adds an overlay which informs the users about the use of cookies. You can add a different text for every available language.' => '',
    'Adds several editable legal options, like an imprint and a privacy policy.' => '',
    'Are you really sure? Please save changes before proceed!' => '',
    'Box content' => '',
    'Box language:' => '',
    'Configuration' => '',
    'Content' => '',
    'Cookie notification' => '',
    'Default languge' => '',
    'Delete my account including my personal data' => '',
    'Enabled pages and features' => '',
    'Go back' => '',
    'Got it!' => '',
    'I am older than 16 years' => '',
    'I have read and agree to the Privacy Policy' => '',
    'I have read and agree to the Terms and Conditions' => '',
    'If you update your Privacy Policy you can use the „Reset confirmation“-Option to inform your users and invite them to reagree. ' => '',
    'If you update your Terms and Conditions you can use the „Reset confirmation“-Option to inform your users and invite them to reagree. ' => '',
    'Imprint' => '',
    'Informs the users that you have changed your Privacy Policy or your Terms and Conditions. In order to trigger it, the „Reset confirmation“-Option of said legal documents need to be activated.' => '',
    'Legal Tools' => '',
    'Legal Update' => '',
    'Logout' => '',
    'More information: {link}' => '',
    'Page language:' => '',
    'Page:' => '',
    'Privacy Policy' => '',
    'Reset confirmation' => '',
    'Reset successful!' => '',
    'Show age verification (16+)' => '',
    'Terms and Conditions' => '',
    'This page is added to the footer navigation and the registration process. You can add a different text for every available language.' => '',
    'Title' => '',
    'Used page language when requested language is not available.' => '',
    'Will be used as default, if the legal texts are not available in the user‘s language.' => '',
];
