<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Will be used as default, if the legal texts are not available in the user�s language.' => '',
    '(Disabled - please add content in default language!)' => '(Deaktiviert - bitte Inhalt für Standardsprache hinzufügen!)',
    '<strong>Legal</strong> module - administration' => '<strong>Legal</strong> Modul- Administration',
    'Accept' => 'Akzeptieren',
    'Accept button label' => 'Beschriftung der Einwillgung',
    'Adds an overlay which informs the users about the use of cookies. You can add a different text for every available language.' => 'Fügt ein Overlay hinzu, welches die Nutzer über die Verwendung von Cookies informiert. Es kann für jede verfügbare Sprache ein gesonderter Text eingestellt werden.',
    'Adds several editable legal options, like an imprint and a privacy policy.' => 'Fügt mehrere Optionen zur rechtssicheren Gestaltung (z.B. Nutzungsbestimmungen) des Netzwerks hinzu.',
    'Are you really sure? Please save changes before proceed!' => 'Bist du sicher? Speichere die Änderungen bitte bevor du fortfährst.',
    'Box content' => 'Inhalt',
    'Box language:' => 'Sprache',
    'Configuration' => 'Konfiguration',
    'Content' => 'Inhalt',
    'Cookie notification' => 'Cookie-Benachrichtigung',
    'Default languge' => 'Standardsprache',
    'Delete my account including my personal data' => 'Löche mein Profil, einschließlich aller persönlicher Daten.',
    'Enabled pages and features' => 'Aktivierte Seiten und Funktionen',
    'Go back' => 'Zurück',
    'Got it!' => 'Verstanden!',
    'I am older than 16 years' => 'Ich bin älter als 16 Jahre!',
    'I have read and agree to the Privacy Policy' => 'Ich habe die Datenschutzbestimmungen gelesen und stimme diesen zu!',
    'I have read and agree to the Terms and Conditions' => 'Ich habe die Nutzungsbedingungen gelesen und stimme diesen zu!',
    'If you update your Privacy Policy you can use the „Reset confirmation“-Option to inform your users and invite them to reagree. ' => 'Wenn die Datenschutzbestimmungen geändert werden kann die Option "Zustimmung zurücksetzen" verwendet werden, um die Änderungen anzuzeigen und eine Einwilligung der Nutzer zu erzwingen.',
    'If you update your Terms and Conditions you can use the „Reset confirmation“-Option to inform your users and invite them to reagree. ' => 'Wenn die Nutzungsbedingungen geändert werden kann die Option "Zustimmung zurücksetzen" verwendet werden, um die Änderungen anzuzeigen und eine Einwilligung der Nutzer zu erzwingen.',
    'Imprint' => 'Impressum',
    'Informs the users that you have changed your Privacy Policy or your Terms and Conditions. In order to trigger it, the „Reset confirmation“-Option of said legal documents need to be activated.' => 'Informiert die Benutzer über Änderungen der Datenschutzbestimmungen bzw. der Nutzungsbedingungen. Um das Anzeigen des Textes auszulösen, muss die Option "Zustimmung zurücksetzen" betätigt werden.',
    'Legal Tools' => 'Legal Tools',
    'Legal Update' => 'Anpassungen',
    'Logout' => 'Logout',
    'More information: {link}' => 'Weitere Informationen: {link}',
    'Page language:' => 'Seitensprache:',
    'Page:' => 'Seite:',
    'Privacy Policy' => 'Datenschutzbestimmugnen',
    'Reset confirmation' => 'Zustimmung zurücksetzen',
    'Reset successful!' => 'Erfolgreich zurückgesetzt! ',
    'Show age verification (16+)' => 'Altersprüfung anzeigen (16+)',
    'Terms and Conditions' => 'Nutzungsbedingungen',
    'This page is added to the footer navigation and the registration process. You can add a different text for every available language.' => 'Diese Seite wird in die Fußnavigation un den Registrierungsprozess eingefügt. Es kann für jede verfügbare Sprache ein gesonderter Text eingestellt werden. ',
    'Title' => 'Titel',
    'Will be used as default, if the legal texts are not available in the user‘s language.' => 'Text wird in der Standardsprache angezeigt, wenn die vom User ausgewählte Sprache keine Inhalt hat.',
];
