<?php

namespace humhub\modules\legal\models;

use Yii;

/**
 * This is the model class for table "legal_page".
 *
 * @property string $page_key
 * @property string $language
 * @property string $title
 * @property string $content
 * @property integer $last_update
 */
class Page extends \yii\db\ActiveRecord
{
    const PAGE_KEY_IMPRINT = 'imprint';
    const PAGE_KEY_TERMS = 'terms';
    const PAGE_KEY_PRIVACY_PROTECTION = 'privacy';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'legal_page';
    }


    public function beforeSave($insert)
    {
        if (empty($this->content)) {
            if (!$this->isNewRecord) {
                $this->delete();
            }

            return false;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'content'], 'safe']
            /*
            [['page_key', 'language', 'title', 'content'], 'required'],
            [['content'], 'string'],
            [['last_update'], 'integer'],
            [['page_key'], 'string', 'max' => 15],
            [['language'], 'string', 'max' => 10],
            [['title'], 'string', 'max' => 255],
            */
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'title' => Yii::t('LegalModule.base', 'Title') . ' (' . $this->language . ')',
            'content' => Yii::t('LegalModule.base', 'Content') . ' (' . $this->language . ')',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return [
            'content' => Yii::t('LegalModule.base', 'Leave empty to delete this page for the selected language.'),
        ];
    }

    /**
     * @return array the menu locations
     */
    public static function getPages()
    {
        return [
            static::PAGE_KEY_IMPRINT => Yii::t('LegalModule.base', 'Imprint'),
            static::PAGE_KEY_TERMS => Yii::t('LegalModule.base', 'Terms and conditions'),
            static::PAGE_KEY_PRIVACY_PROTECTION => Yii::t('LegalModule.base', 'Privacy protection'),
        ];
    }
}
