<?php

namespace humhub\modules\legal\models;

use humhub\components\ActiveRecord;
use humhub\modules\legal\Module;
use Yii;

/**
 * This is the model class for table "legal_page".
 *
 * @property integer $id
 * @property string $page_key
 * @property string $language
 * @property string $title
 * @property string $content
 * @property integer $last_update
 */
class Page extends ActiveRecord
{
    const PAGE_KEY_IMPRINT = 'imprint';
    const PAGE_KEY_TERMS = 'terms';
    const PAGE_KEY_PRIVACY_PROTECTION = 'privacy';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'legal_page';
    }


    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        if (empty($this->title)) {
            $this->title = static::getDefaultPageTitle($this->page_key);
        }

        if (empty($this->content)) {
            if (!$this->isNewRecord) {
                $this->delete();
            }

            return false;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'content'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'title' => Yii::t('LegalModule.base', 'Title') . ' (' . $this->language . ')',
            'content' => Yii::t('LegalModule.base', 'Content') . ' (' . $this->language . ')',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return [
            'content' => Yii::t('LegalModule.base', 'Leave empty to delete this page for the selected language.'),
        ];
    }

    /**
     * @return array the menu locations
     */
    public static function getPages()
    {
        return [
            static::PAGE_KEY_IMPRINT => Yii::t('LegalModule.base', 'Imprint'),
            static::PAGE_KEY_TERMS => Yii::t('LegalModule.base', 'Terms and conditions'),
            static::PAGE_KEY_PRIVACY_PROTECTION => Yii::t('LegalModule.base', 'Privacy protection'),
        ];
    }

    public static function getDefaultPageTitle($pageKey)
    {
        return self::getPages()[$pageKey];
    }

    /**
     * @param string $pageKey
     * @param string $language
     * @return Page|null the page or null
     */
    public static function getPage($pageKey, $language = null)
    {
        if ($language === null) {
            $language = Yii::$app->language;
        }

        $page = Page::findOne(['language' => $language, 'page_key' => $pageKey]);
        if ($page === null) {
            /** @var Module $module */
            $module = Yii::$app->getModule('legal');
            $page = Page::findOne(['language' => $module->getDefaultLanguage(), 'page_key' => $pageKey]);
        }

        return $page;
    }
}
